menu:
    Blog: /
    Archive: /archives/
    about: https://about.me/ching.li
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: ching56

# Analytics
# google-analytics:
ga: UA-100363561-1

# Copyright Infomation
startyear: 2017
